import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "../compontents/header-footer-whatsAPP/Header";
import Footer from "../compontents/header-footer-whatsAPP/Footer";
import WhatsAppButton from "../compontents/header-footer-whatsAPP/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <Header />

        <main className="flex-1">
          {children}
        </main>
         <Footer />
         <WhatsAppButton /> {/* Add this line */}
      </body>
    </html>
  );
}